FROM golang:1.20.4-buster

WORKDIR /app

COPY ./ ./
# COPY go.mod ./

# RUN go mod download
# COPY *.go ./

# WORKDIR /app/src
RUN go install
RUN go build -o /go-docker-demo

# RUN go build -o bin .



# ENTRYPOINT [ "/srcbin" ]
# ENTRYPOINT [ "/sbin" ]

# ENTRYPOINT [ "/bin" ]
CMD [ "/go-docker-demo" ]
# CMD ["go mod run ."]
 